### ISSUE TITLE
storyblok-js-client is not a runtime dependency

### ISSUE THREAD

**Issue by ridem** [storyblok/storyblok-js#207]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

---

## Expected Behavior

End users should be able to update `storyblok-js-client` as per the semver in its `package.json` (currently `^5.2.5`).

## Current Behavior

`storyblok-js-client` is bundled by vite's lib mode by default, so the actual version used by `@storyblok/js` is the one from the last time `storyblok-js-client` was updated and `@storyblok/js` was built. End users need to wait for this to happen and would get unexpected results (for example, thinking an issue would be fixed by upgrading `storyblok-js-client`)

## Solutions to fix it

Either:
- Mark `storyblok-js-client`  as external in vite's config
- Make `storyblok-js-client` part of `devDependencies` and keep upgrading `@storyblok/js` every time `storyblok-js-client` is upgraded

**Comment by fgiuliani** [comment]
Hi @ridem,

The actual behavior is intended. We want to avoid the users having to update `storyblok-js-client` separately, and that's why we are bundling it into `@storyblok/js` and defining a reactive release system that runs every day to keep the dependencies up to date.

cc @alexjoverm
