### ISSUE TITLE
[Issue] Don't include the bridge if we are not in Storyblok (check value _storyblok)

### ISSUE THREAD

**Issue by Dawntraoz** [storyblok/storyblok-js#214]
I create this issue to raise an internal solution or to document the use of the bridge differently to avoid projects loading the bridge in production without necessity and to standardize it between technologies (SDKs).

PR of a community member with an approx for Nuxt 3 -> https://github.com/storyblok/storyblok-nuxt/pull/227

Reference -> https://github.com/storyblok/storyblok-js/blob/5aa2bdb4de93cb2e07959e20c0359cc4f875bb74/lib/index.ts#L19

**Comment by Dawntraoz** [comment]
@thiagosaife, any comments or help on this matter?

**Comment by SebbeJohansson** [comment]
I actually went ahead and made a suggested way to fix this. The only thing I am unsure about is the usage of URLSearchParams, but it should be fine to use it.

**Comment by reinoldus** [comment]
URLSearchParams is not supported by IE11, not sure if this browser is still supported by storyblok client api.
https://caniuse.com/urlsearchparams

**Comment by SebbeJohansson** [comment]
@reinoldus given that ie11 isnt supported by anything pretty much I don't think that should be an issue, but as you said I'm not sure what is supported right now by storyblok-js.
Hopefully, Thaigo or someone can clear up this! I can switch to looking at the full string if needed, but I personally thing making an object makes more sense for readabilty.

**Comment by reinoldus** [comment]
@thiagosaife any update on this matter?

I would like to understand the difficulty of the issue, to me it seems like it's an easy fix, given that there are PRs already.

Couldn't we enable this fix with a configurable option, if you are concerned about compatibility issues?

**Comment by alexjoverm** [comment]
Hey @reinoldus we fixed the thing about the console error that was likely polluting your Sentry in #239.

Keep in mind you can dynamically load the bridge at init time per environment, like this:

```js
storyblokInit({
  bridge: process.env.NODE_ENV !== "production"
})
``` 

However, we'll keep this issue open as it might be a nice feature request :) thanks!

**Comment by reinoldus** [comment]
@alexjoverm 

Thank you, I don't think that is the issue with my sentry but I'll check it out.

But I have to disagree: It's not a "nice to have thing", this library is loading unnecessary JavaScript on to clients which won't be used by anybody if they are not in the storyblok editor.

It's not a huge file, but it is still absolutely unnecessary and fixing it seems very easy to do.

Disabling the bridge is not an option for me, the USP of storyblok for me was that I can edit my live website with ease.

**Comment by SebbeJohansson** [comment]
@alexjoverm I dont understand your suggestion for a fix being to disable the bridge in production. How is that an acceptable fix when I need to be able to run the editor in a built environment for my editors?
It could be that I misunderstood something!

**Comment by reinoldus** [comment]
@alexjoverm 

additional question: How do I test the new version, if I am on storyblok-nuxt2, there hasn't been a release as far as I can tell.

And another thing that I don't understand: The storyblok-nuxt2 module installs as dependencies this module and the vue-module, but those don't seem to be used, because everything seems to be bundled into one dist file.

Deleting those modules from my node_modules dir doesn't seem to break anything it looks like those libs are installed for no reason as well.

This build behavior makes it also hard to just fork the lib and just use @SebbeJohansson fix in a fork.

If you don't wanna fix it, can you explain how the build process works, so we can at least fork?

**Comment by SebbeJohansson** [comment]
@reinoldus there needs to be an update to the vue2 package because the vue2 package is limited to `"@storyblok/js": "^1.8.5"`. The nuxt2 package should get the update right away after vue2 is updated.

**Comment by SebbeJohansson** [comment]
@Dawntraoz Any news on this?

**Comment by alexjoverm** [comment]
@SebbeJohansson @reinoldus we're actually discussing if would make sense to automatically enable/disable the bridge depending on if the frontend is loaded on the visual editor.

The reason we made the bridge conditional is so you can disable it in production. A usual case to use Storyblok is different environments is:
- Preview/Stating: here you use the draft token and you want to load the bridge, so you want the visual editor to be interactive to change content.
- Production: you use public token and don't want the bridge, as actually with the public token the interactivity is disabled.

**Comment by SebbeJohansson** [comment]
@alexjoverm I think that it would make sense. I have a feeling that the most common way to do it is to only run bridge in preview mode despite if it is in a production or dev environment.

How to handle version and the bridge is the most common issue that people have. Mainly that they set version to "published" if it is in production, which means that bridge doesn't function.

**Comment by Dawntraoz** [comment]
@SebbeJohansson I will create a PR today with the new conditional 🎉, and we can adequately add some docs to clarify "published" and Public Token, so people understand that for previewing, they need the "draft" version and the Preview Token, not the production ones.

**Comment by SebbeJohansson** [comment]
@Dawntraoz AMAZING! 🥳

Check #236 and close it if nothing should be kept going from that :)
