### ISSUE TITLE
It's not possible to pass in the endpoint parameter

### ISSUE THREAD

**Issue by philipp-bender** [storyblok/storyblok-js#23]
It's not possible to pass in the optional endpoint string:

`const storyblokApi = new StoryblokClient(apiOptions);
  return { storyblokApi };`

Only apiOptions are supported.

**Comment by fgiuliani** [comment]
Hello @philipp-bender,

I think this change lately introduced should help for that purpose:
https://github.com/storyblok/storyblok-js-client/pull/598

cc @alexjoverm
