### ISSUE TITLE
AxiosError: options must be an object, using latest version of axios

### ISSUE THREAD

**Issue by mastepanoski** [storyblok/storyblok-js#253]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Using @storyblok/js with axios v1 does not work.
---

## Expected Behavior

It is expected that @storyblok/js must be compatible with axios v1.

## Steps to Reproduce

1. Install axios, "yarn add axios".
2. Execute the project (for example, using NextJS and @storyblok/react), and then yarn dev.
3. The following error is shown: AxiosError: options must be an object.

**Comment by Dawntraoz** [comment]
Hi, @mastepanoski axios is no longer needed. We are using native fetch since https://github.com/storyblok/storyblok-js/releases/tag/v2.0.0

Did you upgrade @storyblok/js already? I hope it helps 🚀

**Comment by Dawntraoz** [comment]
I will close this issue since axios is no longer a dependency
