### ISSUE TITLE
'Header is  not defined error' when using Storyblok API client from version 2.1.0 in AWS lambda  

### ISSUE THREAD

**Issue by kethzi-gilbert** [storyblok/storyblok-js#256]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

---
I observe an error when I create a AWS Lambda function which fetches stories data from a storyblok space using Storyblok API Client. This lambda is triggered using an API on AWS API Gateway. I receive the error "ReferenceError: Headers is not defined" (shown in the screenshot below).
**This error is observed only when i use "@storyblok/js"  version 2.1.0. When i downgrade the library version to 1.8.5, i don't see this error**.

## Expected Behavior

Should be able to fetch the stories from the API in the lambda function.

## Current Behavior
I receive the below error 
![image](https://user-images.githubusercontent.com/114938876/225908806-41fb3184-8520-4e45-be95-4936d06cee40.png)

The lambda Handler code is as below

<img width="659" alt="image" src="https://user-images.githubusercontent.com/114938876/225922633-d117b339-e40d-45e1-a696-dbaeb8b063e5.png">

![image](https://user-images.githubusercontent.com/114938876/225922309-6b9b913a-3485-4cef-888e-0b48dc015226.png)

**Comment by SebbeJohansson** [comment]
I am seeing the same issue in Vue/Nuxt3.
![image](https://user-images.githubusercontent.com/5083273/229592644-a7b15d72-6015-46bb-988f-de48bf83dfd1.png)
![image](https://user-images.githubusercontent.com/5083273/229592608-3d9e109a-fab3-49b7-ad79-fc83d537d653.png)

**Comment by thomas-ef** [comment]
Same error here

**Comment by henrykuijpers** [comment]
@kethzi-gilbert Did you try https://www.storyblok.com/faq/headers-not-defined-storyblok-sdk ?

**Comment by SebbeJohansson** [comment]
I have not tested, but Im pretty sure I was running nodejs 18 so I shouldn't have to do the polymorph. But as I said, I haven't tested it in a long time. Might be that I was running it weirdly or something. Nuxt3 should be working fine now.
