### ISSUE TITLE
Storyblok Bridge resolveLinks option

### ISSUE THREAD

**Issue by Rigo-m** [storyblok/storyblok-js#317]
### Description

Internally, we have created a nuxt server api that re-fetches story data whenever storyblok bridge gives the input, changed or published events. This provides us with fresh data without reloading the page. (We are currently using a custom made setup that leverages storyblok graphql api, hence the need to customly handle bridge updates).
Long story short, our graphql apis are set with resolveLinks: "story", while bridge resolve links as urls.

### Suggested solution or improvement

Add a resolveLinks parameter to the storyblokBridge class

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by fgiuliani** [comment]
Hi @Rigo-m,
We added that functionality a few weeks ago. Can you check it's working for you?

https://github.com/storyblok/storyblok-js/commit/4ff2a523e69d7310e8b2d6d7a595190ddb1b95bc
