### ISSUE TITLE
[renderRichText] A new line at the beginning without content causes problems

### ISSUE THREAD

**Issue by DevJoghurt** [storyblok/storyblok-js#318]
### Describe the issue you're facing

A new line at the beginning without content causes renderRichText to return an empty string for all rendered content.
Sometimes it is also desired to insert a blank line at the beginning of the text to increase the spacing. This is no longer possible after the last changes to the lib.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ngu3pb?file=src%2FApp.vue

### Steps to reproduce

Add a line at the beginning of your document, just like in the stackblitz reproduction

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by fgiuliani** [comment]
Hi @DevJoghurt thanks for submitting. 

You say this is not working anymore "after the last changes to the lib". Was it working before? Were you able to identify what was the last version this functionality was working properly?

**Comment by DevJoghurt** [comment]
@fgiuliani 
Thanks for coming back to me.
Last working version is 2.1.6.

**Comment by fgiuliani** [comment]
Hey @DevJoghurt,
@Baheya created this PR that, when merged, should solve the issue:
https://github.com/storyblok/storyblok-js/pull/341

**Comment by fgiuliani** [comment]
@DevJoghurt PR merged! Can you update to the latest version and check if now it's working for you?

**Comment by Dawntraoz** [comment]
Since @DevJoghurt reacted to the Facundo comment with a thumbs up we can close the issue as resolved.
