### ISSUE TITLE
Process is not defined

### ISSUE THREAD

**Issue by rickvandermeij-aanzee** [storyblok/storyblok-js#337]
### Describe the issue you're facing

After updating to 2.2.3 process.env is not defined. Why do we need this in our project. 
Sure thing you'll need it in cypress, but that should be a different config for your e2e

We had to inject this Polyfill:
```
// eslint-disable-next-line @typescript-eslint/no-explicit-any
(window as any).process = {
	env: { DEBUG: undefined },
};
```

### Reproduction

none

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 26.89 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.3.1 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by fgiuliani** [comment]
Hi @rickvandermeij-aanzee thanks for submitting this issue.

When are you getting that error?

**Comment by fgiuliani** [comment]
Hi @rickvandermeij-aanzee we just released a new version of the SDK that includes a fix for this problem.

Can you update to the latest version of the SDK and check if it works for you now?

**Comment by rickvandermeij-aanzee** [comment]
after updating to 2.2.10 the error is gone without the use of the polyfill
