### ISSUE TITLE
Error in SbSDKOptions type definition

### ISSUE THREAD

**Issue by czajkowski** [storyblok/storyblok-js#61]
There is an error in SbSDKOptions type definition that specifies the type of 'use'.

`use?: [];` means this may be an empty array.

When you pass anything in use TS reports an error:
Type '{}' is not assignable to type 'undefined'.

Here is an example:
https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDeBYAUFKBXAzhA-AFxQDaAuugL4Dc66AxgPYB2OwUYAhgE6cC2CZDTpomrdp0JxESbHmIkuvPmWFogA

If you don't specify any types for plugins you could probably change that to: `use?: any[]`

**Comment by fgiuliani** [comment]
Closing this PR as the change was already introduced:
https://github.com/storyblok/storyblok-js/blob/ca8d32e5790a399290167be2c0849424ad0c5821/lib/types.ts#L35
