### ISSUE TITLE
Cannot add property `accessToken`, object is not extensible

### ISSUE THREAD

**Issue by arpadgabor** [storyblok/storyblok-js#63]
As mentioned in https://github.com/storyblok/storyblok-nuxt/issues/149 , there is an issue with the `pluginOptions` object in `storyblokInit`. More specifically, this piece of code:

https://github.com/storyblok/storyblok-js/blob/e6e4522e72309e7c67d8495859202cbad269475b/lib/index.ts#L49-L52

When trying to use `storyblok-nuxt` with Nuxt 3 and passing in the `apiOptions` to the module we get the error: `Cannot add property accessToken, object is not extensible`. I think somewhere in the plugin pipeline for Nuxt we hit a [`Object.preventExtensions()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/preventExtensions).

**Comment by StaffOfHades** [comment]
This should be fixed as of `V4.3.0`. Check https://github.com/storyblok/storyblok-nuxt/issues/170#issuecomment-1239527769
