### ISSUE TITLE
Multiple Stories per window, window.reload()

### ISSUE THREAD

**Issue by albatrocity** [storyblok/storyblok-js#65]
I use this library by way of `@storyblok/react` and `gatsby-source-storyblok`. I'm very excited to have low-config support for the Storyblok bridge with the `useStoryblokState` hook. However, I'm running into an issue with my use case.

I use different stories for different parts of a website layout: one for the site header, one for the site footer, one for each page. This way I can have my fixed layout elements managed in Storyblok. It works great and it's a killer feature or Storyblok in general. Previously I was initializing my own bridge and dispatching story changes to redux. While upgrading `gatsby-source-storyblok` and finding the `useStoryblokState` hook, I started to implement it throughout my project so I could ditch my custom bridge implementation and my reliance on Redux for preview state. 

However, when I `useStoryblokState` on more than one story rendered on a page, each Bridge instance [thinks it's not on the right page and reloads the page](https://github.com/storyblok/storyblok-js/blob/main/lib/index.ts#L37-L42). This doesn't seem to be configurable from `gatsby-source-storyblok` down.

Are there any considerations for supporting multiple stories per window, or at least a way to configure the [bridge event handlers](https://github.com/storyblok/storyblok-js/blob/main/lib/index.ts#L36) from a higher-level library? I know I can disable the bridge from `gatsby-source-storyblok` and implement my own, but I'd love to use the internal per-story state implemented by the library. Currently my page just reloads every time I make a change in the editor.

Thanks for this plugin and any insight you can provide!

**Comment by victor-ru** [comment]
Hi @albatrocity!
I'm facing a similar issue. Have you found a way to make this work correctly? Thank you!

**Comment by albatrocity** [comment]
@victor-ru unfortunately not! I've just been enduring it 😄

**Comment by fgiuliani** [comment]
Hello @albatrocity sorry for the late response.
Can you update the version of the SDK and verify if this keeps happening? We introduced some changes lately that should stop that issue to happen:
https://github.com/storyblok/storyblok-js/commit/761af2c49174b55b577d577fb66ddb6d153b8cf8

Having said that, a recommendation we share is to only call the `useStoryblokState` React Hook only once per page. In your case, you could retrieve and render Header and Footer stories without using `useStoryblokState` hook with them.
